---
title: "Quant - Assignment 1"
author: "Cat"
date: "8/13/2020"
output: html_document
---
## Load Packages and Data

```{r}
library(tidycensus)
library(tidyverse)
```


```{r}
options(tigris_use_cache = TRUE)
census_api_key("f96e31b3e535fc7cd31223fcf140d31f8f1bfe76", overwrite = TRUE, install = TRUE)

readRenviron("~/.Renviron")
```


## Finding Variables 
```{r}
person_vars_2018 <- pums_variables %>%
  distinct(year, survey, var_code, 
           var_label, data_type, level) %>%
  filter(level == "person", year == 2018, survey == "acs1")
```

```{r}
hh_vars_2018 <- pums_variables %>%
  distinct(year, survey, var_code, 
           var_label, data_type, level) %>%
  filter(level == "housing", year == 2018, survey == "acs1")
```

```{r}
area_vars_2018 <- load_variables(2018, "acs1")
```
```{r}
area_vars_2010 <- load_variables(2010, "sf1")
```
#variables used: Percent of population with a college degree (age 25 to 64) (continuous), Unemployment rate (age 16 and over) (continuous), Median income (continuous), Racial composition (majority white or majority minority) (categorical), Rural (100% rural population from 2010 census) (categorical)
```{r}
pop_vars <- c(workers_16= "B23025_002", 
              unemp_pop_16= "B23025_005", 
              college_25= "B23006_023", 
              popln_25="B23006_001", 
              med_income = "B06011_001", 
              tot_pop= "B01003_001", 
              white_pop= "B01001A_001")

rural_vars <- c(total_hh= "H002001", 
                rural_hh= "H002005")

counties2018 <- get_acs(geography= "county", 
                        variables= pop_vars, 
                        output= "wide", 
                        year = 2018, 
                        survey= "acs1")

counties_rural <- get_decennial(geography= "county", 
                                variables= rural_vars, 
                                output= "wide", 
                                year = 2010)
```
# Join variables into a data frame 

```{r}
counties <- inner_join(counties2018, counties_rural, by = "GEOID") %>% 
  mutate(pct_college = college_25E/ popln_25E, 
         unemp_rate = unemp_pop_16E / workers_16E, 
         majority_white = white_popE / tot_popE > 0.5, 
         rural = rural_hh == total_hh) %>% 
  select(pct_college, unemp_rate, med_incomeE, majority_white, rural)

write_csv(counties,"counties.csv")
```
